version: '3.5'
services:
  postgres:
    image: "${image}"
    restart: always
    network_mode: "host"
    volumes:
      - "${data}:${data}"
      - "/opt/postgres/pg.key:/opt/pg.key"
      - "/opt/postgres/pg.pem:/opt/pg.pem"
%{ if params != "" ~}
    command: ${params}
%{ endif ~}
    environment:
      PGDATA:            "${data}"
      POSTGRES_USER:     "${user}"
      POSTGRES_PASSWORD: "${password}"
      POSTGRES_DB:       "${database}"
%{ if fluentd.enabled ~}
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:${fluentd.port}
        fluentd-retry-wait: 1s
        fluentd-max-retries: 3600
        fluentd-sub-second-precision: true
        tag: ${fluentd.tag}
%{ endif ~}
